### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by sqeezy** [cake-contrib/Cake.Graph#1]
As someone who would like this addin for Cake very much and would be eager to help, I'd like you to define somewhat of a roadmap or at least a description regarding goals and used technologies for this project.

**Comment by wozzo** [comment]
Hey, thanks for your interest.
The next steps I'd planned to do were:
- Improve documentation around usage/deployment
- Add fluent methods for settings
- Add some unit tests
- Get it added to Cake.Recipe
Am very much open to suggestions
Longer term / Harder:
- Allow the graph to scale based on number of dependencies/complexity
- Add a different view which displays a list (as opposed to graph) of tasks in the order cake would run them

**Comment by sqeezy** [comment]
I'm currently struggeling to get a quick wyam test in. I will join in after the first usage/deployment documentation is present. Looking forward to it.

**Comment by wozzo** [comment]
@sqeezy New version is out [0.2.0](https://www.nuget.org/packages/Cake.Graph/0.2.0) with a bug fix and improved [usage](https://cake-contrib.github.io/Cake.Graph/docs/usage) page. I've also added the list of todos I put above on the [readme](https://cake-contrib.github.io/Cake.Graph/about)

**Comment by sqeezy** [comment]
Could you supply an example for standing up the wyam environment? This is what really hinders me now. Just so anybody can try this out in under 10 minutes.

**Comment by wozzo** [comment]
This blog post will hopefully set you in the right direction. http://wbates.net/posts/setting-up-a-wyam-blog-with-cake-recipe-and-github-pages
Checking what's in the docs folder in this repo should also help. 
Or you can do it without wyam and just run a http server pointed at the output.

**Comment by gep13** [comment]
Another option would be to use Cake.Wyam.Recipe, which is more aimed at Wyam specifically, and doesn't include all the MSBuild related tasks, etc.  That way, if you are solely doing a Wyam blog, it is a better fit.
