### ISSUE TITLE
Target netstandard2.0 to run with CoreCLR

### ISSUE THREAD

**Issue by vhatsura** [cake-contrib/Cake.Graph#16]
Hi, guys.

It would be awesome, if Cake.Graph will target netstandard2.0. It will allow to use Cake.Graph with Cake.CoreCLR host. 

Maybe you know any issues which is affected migration to netstandard2.0.
If you don't have a free time, I would happy to make changes regarding targeting netstandard2.0.

**Comment by wozzo** [comment]
@vhatsura I'm not aware of any issues that would stop it targeting netstandard2.0. Will gladly PR if you come up with something :)

**Comment by vhatsura** [comment]
@wozzo, will you have a chance to look at #17 PR?

**Comment by wozzo** [comment]
I'll endeavour to take a look at the weekend. Seems like you've made some cool changes
________________________________

**Comment by vhatsura** [comment]
Hi, @wozzo.

Thanks for merging my changes. When are you going to release them?

**Comment by vhatsura** [comment]
Close issue due to 0.7.0 version was released

**Comment by vhatsura** [comment]
Sorry, but cannot find 0.7.0 version in [nuget.org](https://www.nuget.org/packages/Cake.Graph/)

**Comment by wozzo** [comment]
Yeah. I spotted that this morning. Will try to look shortly to see what's gone wrong
________________________________

**Comment by wozzo** [comment]
Manually added to nuget just now. Should be there in the next few minutes. There'll be a 0.7.1 to follow targeting cake 0.30.0
