### ISSUE TITLE
0.7.0 - could not load RazorLight dll

### ISSUE THREAD

**Issue by awelburn** [cake-contrib/Cake.Graph#21]
Could not load D:\projects\git\merges\_tools\Addins\Cake.Graph.0.7.0\lib\netstandard2.0\Cake.Graph.dll (missing RazorLight, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null)

I think the problem might be resolved by adding the dependency to the nuspec file so nuget will automatically pull that package as well?

**Comment by wozzo** [comment]
@awelburn 0.7.1 released with the fix - you'll also need to add the loaddependencies setting to the addin preprocessor directive.
```
#addin Cake.Graph&loaddependencies=true
```
