### ISSUE TITLE
Support mermaid graphs

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.Graph#7]
Wyam themes like Samson for the docs recipie have [mermaid](https://mermaidjs.github.io/) included by default. Would be nice if Cake.Graph could generate Markdown files with mermaid syntax to avoid having to use another graph engine in the same site.

**Comment by wozzo** [comment]
I agree, this looks promising. I'll try a few things out, but I'm away soon so it'll likely be late November before I'll make any real progress with this.

**Comment by wozzo** [comment]
Lots of progress on this now. Mermaid for wyam is the default (produces an md file for each task)
But the generator can be switched out to produce cytoscape json files, or individual html files for either cytoscape or mermaid that won't require wyam.
Want to add some unit tests and additional examples to documentation before I merge to master and release.
