### ISSUE TITLE
Update Cake.Graph to use 0.23.0

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.Graph#8]
In the latest release of Cake there were some changes to the way Tasks can be constructed. As a result, if you try to use Cake.Graph when running 0.23.0 you will run into this:

https://github.com/cake-contrib/Cake.Webpack/pull/7

@wozzo any chance you can update Cake.Graph to account for this change?  Thanks.

**Comment by wozzo** [comment]
Will take a look.

**Comment by wozzo** [comment]
Should be upgraded now. Let me know if there are ongoing problems.
